### PR TITLE
replacing existing icon with one that better matches the brackets design

### LINKED ISSUE #38: can we please have a nicer icon?
The Brackets sidebar icons #BBBBBB (187 for all 3 rgb values), and the NPM icon is white with a dark gray border. It looks out of place.

At the very least, changing the CSS to include a brightness filter would be better, as such:

```css
-webkit-filter: grayscale(100%) brightness(80%);
```

However, getting a better icon that fits the style of Brackets more would be good. I would be willing to make one if you are on board.

### PR DESCRIPTION
**Pull request by catdad**
Fixes #38.

I added a new icons for the default and active states. It uses a Brackets-style "lego block" icon (like the default plugin icon), with NPM's "n" icon inside it. It's too cramped and unreadable to fit 3 letters inside a 20x20 icon, and the "n" icon is commonly used for smaller NPM icons.

Links to the icons:
[default gray icon](https://github.com/catdad/brackets-npm-registry/blob/master/styles/icon.svg)
[active icon](https://github.com/catdad/brackets-npm-registry/blob/master/styles/icon-active.svg)

### CODE REVIEW

**Comment by zaggino** [comment]
:+1:

**Comment by zaggino** [comment]
Published as 0.5.1

**Comment by zaggino** [comment]
@catdad not sure if it's just me, or is the normal registry icon bigger (height)?

image

**Comment by catdad** [comment]
It shouldn't be. The red doesn't stand out well against the gray, which makes the icon look slimmer all around. I actually had to make the red a lot brighter than the standard NPM red color. The gray and red icons both use the exact same block shape.

**Comment by catdad** [comment]
Actually, you are not necessarily wrong. You might be onto something.

sizes

The normal registry icon is not taller, but it is about a pixel down from the one I made. I can fix that.

**Comment by zaggino** [comment]
Thanks, it just popped into my eyes, I wasn't measuring anything :)

**Pull request merged**
